---

- name: ensure node key present
  apt_key:
          url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
          id: "68576280"
          state: present

- name: ensure apt-transport-https
  apt:
          name: apt-transport-https
          state: present
                  
- name: ensure nodejs version in deb repo
  apt_repository:
          repo: "{{ item }}"
          state: present
  with_items:
          - "deb https://deb.nodesource.com/node_7.x stretch main"
          - "deb-src https://deb.nodesource.com/node_7.x stretch main"

- name: update deb repo
  apt:
          update_cache: yes

- name: ensure dependencies install
  apt:
          name: "{{ item }}"
          state: latest
  with_items:
          - git
          - curl
          - build-essential
          - nodejs
          - supervisor

- name: ensure supervisor nodemon
  npm:
          name: nodemon
          global: yes
          production: yes
          state: present

