---
- include_tasks: install_deps.yml

- include_tasks: django.yml

- name: ensure nginx configure is correct
  template:
          src: nginx_http_conf.j2
          dest: /etc/nginx/sites-available/default

- name: ensure upstream servers present
  template:
          src: upstream.j2
          dest: /etc/nginx/conf.d/default.conf
  notify:
          - restart nginx


